import { BriefData } from '../../types/brief';

/**
 * LEGACY FILE - Partiellement utilisé
 * generateCreativeBriefs: Deprecated - Remplacé par PostGenerationService
 * generateVisualAnalysis: ACTIF - Utilisé par services/ai/index.ts
 */

interface ThemeData {
  name: string;
  objective: string;
  approach: string;
  emotions: string;
  formats: string[];
  networks: string[];
}

/**
 * DEPRECATED - Kept for backward compatibility only
 * Use PostGenerationService for new implementations
 */
export const generateCreativeBriefs = (
  briefData: BriefData, 
  themes: ThemeData[], 
  startIndex: number = 0, 
  batchSize: number = 4
): string => {
  return `LEGACY CREATIVE BRIEFS GENERATOR - DEPRECATED
  
This function is deprecated and kept for compatibility only.
Creative briefs are now generated by PostGenerationService using the new 3-level architecture.

Brand: ${briefData.companyName}
Sector: ${briefData.sector}
`;
};

/**
 * ACTIVE FUNCTION - Analyse visuelle de la marque
 * Adapté à la nouvelle architecture 3 niveaux (Brand only)
 * Note: Informations Product et Calendar seront ajoutées par les services
 */
export const generateVisualAnalysis = (briefData: BriefData): string => {
  // Construction contexte historique
  const historySection = briefData.previousCampaigns && briefData.previousCampaigns.length > 0 ? `
HISTORIQUE VISUEL DES CAMPAGNES:
${briefData.previousCampaigns.map(campaign => `
${campaign.name} (${campaign.period}):
- Résultats visuels: ${campaign.results.join(', ')}
- Learnings créatifs: ${campaign.learnings.join(', ')}`).join('\n')}
` : '';

  // Construction analyse concurrentielle
  const competitiveSection = briefData.competitiveAnalysis ? `
ANALYSE CONCURRENTIELLE VISUELLE:
${briefData.competitiveAnalysis.directCompetitors?.map(competitor => `
${competitor.name}:
- Signatures visuelles: ${competitor.strengths.join(', ')}
- Stratégies créatives: ${competitor.strategies.join(', ')}`).join('\n') || 'Aucun concurrent direct analysé'}

Position différenciante: ${briefData.competitiveAnalysis.marketPosition || 'Non définie'}
Opportunités créatives: ${briefData.competitiveAnalysis.opportunities?.join(', ') || 'À identifier'}
` : '';

  // Construction cadre légal
  const legalSection = briefData.legalConstraints ? `
CONTRAINTES LÉGALES VISUELLES:
Réglementations: ${briefData.legalConstraints.regulations.join(', ')}
Compliance: ${briefData.legalConstraints.compliance.join(', ')}
Mentions obligatoires: ${briefData.legalConstraints.disclaimers.join(', ')}
` : '';

  return `
╔════════════════════════════════════════════════════════════════════════╗
║                                                                        ║
║          ANALYSE VISUELLE MARQUE - STANDARD CANNES LIONS              ║
║          Optimisé pour IA Générative (Stability AI, Midjourney)       ║
║                                                                        ║
╚════════════════════════════════════════════════════════════════════════╝

En tant que directeur artistique primé aux Cannes Lions et expert en IA générative, 
analysez les éléments visuels de la marque et générez des recommandations 
détaillées optimisées pour la génération d'images par IA.

═══════════════════════════════════════
IDENTITÉ DE MARQUE
═══════════════════════════════════════

INFORMATIONS CORPORATE:
Marque: ${briefData.companyName}
Secteur: ${briefData.sector}
Positionnement stratégique: ${briefData.businessType || 'Non spécifié'} / ${briefData.companyStage || 'Non spécifié'} / ${briefData.pricePositioning || 'Non spécifié'}

DESCRIPTION & ADN:
${briefData.companyDescription}

${briefData.values ? `VALEURS DE MARQUE:
${briefData.values.map(v => `• ${v}`).join('\n')}
` : ''}

${briefData.mission ? `MISSION:
${briefData.mission}
` : ''}

PALETTE DE MARQUE:
${briefData.colors ? `
• Couleur principale: ${briefData.colors.primary || 'Non définie'} ${briefData.colors.primary ? `(HEX: ${briefData.colors.primary})` : ''}
• Couleur secondaire: ${briefData.colors.secondary || 'Non définie'} ${briefData.colors.secondary ? `(HEX: ${briefData.colors.secondary})` : ''}
• Couleur accent: ${briefData.colors.accent || 'Non définie'} ${briefData.colors.accent ? `(HEX: ${briefData.colors.accent})` : ''}
` : 'Palette de marque non définie - À développer dans l\'analyse'}

${historySection}

${competitiveSection}

${legalSection}

═══════════════════════════════════════
MISSION D'ANALYSE
═══════════════════════════════════════

Sur la base de ces informations de MARQUE, développez une analyse visuelle 
complète et des recommandations créatives pour alimenter la génération de 
contenu visuel par IA générative.

NOTE: Cette analyse se concentre sur l'ADN MARQUE. Les informations PRODUIT 
(photos, caractéristiques) et CALENDRIER (réseaux sociaux, formats) seront 
intégrées ultérieurement par les services appropriés.

═══════════════════════════════════════
FRAMEWORK D'ANALYSE ATTENDU
═══════════════════════════════════════

1️⃣ IDENTITÉ VISUELLE STRATÉGIQUE

A. PALETTE COULEURS ÉTENDUE (Codes HEX précis)
   → Palette principale harmonisée (3-5 couleurs)
   → Palette secondaire complémentaire (3-4 couleurs)
   → Couleurs d'accent stratégiques (2-3 couleurs)
   → Proportions recommandées (%)
   → Associations émotionnelles par couleur
   → Gradients de marque signature
   → Conformité avec cadre légal sectoriel

B. TYPOGRAPHIE & HIÉRARCHIE VISUELLE
   → Familles de polices principales (avec alternatives IA)
   → Polices secondaires et d'accent
   → Hiérarchie typographique (H1, H2, body, captions)
   → Tailles et espacements optimaux
   → Styles de caractères (bold, italic, regular)
   → Lisibilité mentions légales (taille min, contraste)
   → Guidelines pour textes générés par IA

C. SYSTÈME ICONOGRAPHIQUE
   → Style d'iconographie (flat, outline, gradient, 3D)
   → Épaisseur traits et niveau de détail
   → Angles, courbes, coins (arrondis vs sharp)
   → Cohérence visuelle cross-canal
   → Symboles réglementaires obligatoires
   → Prompts IA pour générer icônes cohérentes

2️⃣ DIRECTION PHOTOGRAPHIQUE & COMPOSITION

A. STYLE PHOTOGRAPHIQUE SIGNATURE
   → Genre photographique (lifestyle, studio, documentary, conceptual)
   → Niveau de stylisation (naturel, stylisé, surréaliste)
   → Traitement des textures (smooth, grainy, sharp)
   → Profondeur de champ préférée
   → Bokeh et flou artistique
   → Post-processing signature

B. COMPOSITION & CADRAGE
   → Règles de composition (tiers, golden ratio, centré)
   → Points d'intérêt et focales
   → Lignes de force et perspectives
   → Équilibre des masses visuelles
   → Espaces négatifs stratégiques
   → Zones réservées mentions légales (safe zones)

C. ÉCLAIRAGE & ATMOSPHÈRE
   → Style d'éclairage (naturel, studio, dramatique, soft)
   → Direction lumière principale (front, side, back, top)
   → Contraste et dynamique
   → Température couleur (warm, neutral, cool)
   → Mood et ambiance cible
   → Effets lumineux signature

3️⃣ TERRITOIRES VISUELS DE MARQUE

A. UNIVERS ESTHÉTIQUES (min. 3 territoires)
   → Définir 3-5 univers visuels cohérents avec ADN marque
   → Pour chaque univers:
     * Moodboard keywords
     * Références artistiques/culturelles
     * Palette dominante
     * Style photographique
     * Contextes d'usage

B. ÉLÉMENTS RÉCURRENTS DE MARQUE
   → Patterns et textures signature
   → Formes et géométries caractéristiques
   → Effets visuels distinctifs
   → Signatures graphiques
   → Brand assets intégrables

C. ÉVOLUTIONS CRÉATIVES RECOMMANDÉES
   → Tendances émergentes alignées avec marque
   → Innovations visuelles secteur
   → Expérimentations conseillées
   → Risks créatifs calculés

4️⃣ PROMPTS OPTIMISÉS IA GÉNÉRATIVE

A. MASTER PROMPTS PAR STYLE (min. 5 prompts)
   → Prompt base identité marque
   → Variations par univers visuel
   → Negative prompts essentiels
   → Paramètres techniques (CFG, steps, sampler)
   → Keywords magiques pour cohérence

B. PROMPTS SPÉCIFIQUES PAR CONTEXTE
   → Hero visuals / Key visuals
   → Contenu social media
   → Assets promotionnels
   → Backgrounds / Textures
   → Product integration contexts

C. GUIDELINES GÉNÉRATION IA
   → Modèles IA recommandés (Stable Diffusion, Midjourney, DALL-E)
   → Settings optimaux par use case
   → Techniques de consistency (seeds, img2img, ControlNet)
   → Post-processing nécessaire
   → Quality control checklist

5️⃣ CONFORMITÉ & VALIDATION

A. CHECK-LIST RÉGLEMENTAIRE VISUELLE
   → Symboles obligatoires et placement
   → Taille minimale mentions légales
   → Contraste requis pour lisibilité
   → Zones interdites (produits tabac, alcool si applicable)
   → Warnings visuels sectoriels

B. PROCESS DE VALIDATION
   → Étapes d'approbation créative
   → Points de contrôle légal
   → Documentation requise
   → Archivage des assets

C. ADAPTATIONS CROSS-CANAL
   → Déclinaisons par format (square, portrait, landscape, stories)
   → Optimisations par plateforme
   → Responsive guidelines
   → Accessibilité (WCAG AA minimum)

═══════════════════════════════════════
VALIDATION QUALITÉ CANNES LIONS
═══════════════════════════════════════

Chaque recommandation doit être:

✓ INSIGHT-DRIVEN
  → Basée sur ADN marque, positionnement, historique
  → Différenciante vs. concurrence analysée
  
✓ TECHNIQUEMENT PRÉCISE
  → Valeurs numériques exactes (HEX, tailles, ratios)
  → Paramètres IA reproductibles
  → Guidelines claires et actionnables
  
✓ CRÉATIVEMENT AMBITIEUSE
  → Viser excellence Cannes Lions
  → Innovation vs. codes secteur
  → Mémorable et distinctive
  
✓ LÉGALEMENT CONFORME
  → Respect total cadre réglementaire
  → Mentions intégrées créativement
  → Risk mitigation
  
✓ SCALABLE & COHÉRENTE
  → Système visuel évolutif
  → Cohérence cross-canal garantie
  → Efficace pour génération IA en volume

═══════════════════════════════════════
FORMAT DE RÉPONSE
═══════════════════════════════════════

• Structurer avec numérotation claire (1.A.1, 1.A.2, etc.)
• Fournir valeurs numériques précises (codes HEX, px, %, degrés)
• Inclure prompts IA copy-pastables
• Justifier chaque choix par insights marque/marché
• Intégrer systématiquement dimension légale
• Penser en termes de génération automatisée par IA
• Viser cohérence visuelle à grande échelle

═══════════════════════════════════════

READY TO BUILD A CANNES LIONS VISUAL IDENTITY 🦁🎨✨
`;
};
