import { BriefData } from '../../types/brief';

/**
 * LEGACY FILE - Not actively used in current implementation
 * Social media strategy is now handled by PostGenerationService
 * This file is kept for backward compatibility only
 */
export const generateSocialMediaStrategy = (briefData: BriefData): string => {
  return `LEGACY SOCIAL MEDIA STRATEGY GENERATOR - DEPRECATED
  
This function is deprecated and kept for compatibility only.
Social media strategy is now generated by PostGenerationService using the new 3-level architecture.

Brand: ${briefData.companyName}
Sector: ${briefData.sector}
`;
};
